#By default, the hello-kubernetes app listens on port 8080. If you have a requirement for the app to listen on another port, you can specify the port via an env variable. Also update the containerPort value to match.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  selector:
    matchLabels:
      app: hello-app
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-kubernetes
#        image: balogsen/hello-kubernetes:1.10
        image: balogsen/hello-kubernetes:1.10
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: "Hello Seun, It always seems impossible until it's done: Nelson Mandela"
#        - name: PORT
#          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
#    nodePort: 32000
    protocol: TCP
  selector:
    app: hello-app
