apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask
  namespace: default
spec:
  selector:
    matchLabels:
      app: python-flask
  replicas: 2
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
      - name: python-flask
        image: balogsen/python-flask-docker:latest

---
apiVersion: v1
kind: Service
metadata:
  name: python-flask-service
  namespace: default
  labels:
    app: python-flask
spec:
  type: LoadBalancer
  selector:
    app: python-flask
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
